import { FilterTypes } from "../Table/TableFilter/types";

export const dashboardTableCells = [
  {
    id: "name",
    numeric: false,
    disablePadding: false,
    label: "Kierowca",
    filterType: FilterTypes.SELECT,
  },
  {
    id: "profitBolt",
    numeric: false,
    disablePadding: false,
    label: "Obrot Bolt",
    background: "#126aae",
  },
  {
    id: "cashBolt",
    numeric: false,
    disablePadding: false,
    label: "Gotowka Bolt",
    background: "#126aae",
  },
  {
    id: "bonusBolt",
    numeric: false,
    disablePadding: true,
    label: "Bonus Bolt",
    background: "#126aae",
  },
  {
    id: "profitUber",
    numeric: false,
    disablePadding: false,
    label: "Obrot Uber",
    background: "#71b24e",
  },
  {
    id: "cashUber",
    numeric: false,
    disablePadding: false,
    label: "Gotowka Uber",
    background: "#71b24e",
  },
  {
    id: "bonusUber",
    numeric: false,
    disablePadding: true,
    label: "Bonus Uber",
    background: "#71b24e",
  },
  {
    id: "profitFn",
    numeric: false,
    disablePadding: false,
    label: "Obrot Freenow",
    background: "#fd0300",
  },
  {
    id: "cashFn",
    numeric: false,
    disablePadding: false,
    label: "Gotowka Freenow",
    background: "#fd0300",
  },
  {
    id: "bonusFn",
    numeric: false,
    disablePadding: false,
    label: "Bonus Freenow",
    background: "#fd0300",
  },
  {
    id: "vat",
    numeric: false,
    disablePadding: false,
    label: "VAT",
  },
  {
    id: "vatBonus",
    numeric: false,
    disablePadding: true,
    label: "VAT(BONUSY)",
  },
  {
    id: "comission",
    numeric: false,
    disablePadding: true,
    label: "Prowizja Kartell",
  },
  {
    id: "rent",
    numeric: false,
    disablePadding: true,
    label: "Wynajem",
    background: "#fbff02",
  },
  {
    id: "adjustments",
    numeric: false,
    disablePadding: true,
    label: "Regulacja",
    background: "#fbff02",
  },
  {
    id: "salary",
    numeric: false,
    disablePadding: false,
    label: "Wyplata kierowcy",
    background: "#212121",
    color: "#fff",
  },
  {
    id: "paymentType",
    numeric: false,
    disablePadding: false,
    label: "Sposob wyplaty",
  },
];
